/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './../../routes/__root'
import { Route as LayoutImport } from './../../routes/_layout'
import { Route as IndexImport } from './../../routes/index'
import { Route as LayoutSolveImport } from './../../routes/_layout.solve'
import { Route as LayoutCreateImport } from './../../routes/_layout.create'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutSolveRoute = LayoutSolveImport.update({
  path: '/solve',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCreateRoute = LayoutCreateImport.update({
  path: '/create',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/create': {
      preLoaderRoute: typeof LayoutCreateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/solve': {
      preLoaderRoute: typeof LayoutSolveImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([LayoutCreateRoute, LayoutSolveRoute]),
])

/* prettier-ignore-end */
