/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './../../routes/__root'
import { Route as IndexImport } from './../../routes/index'

// Create Virtual Routes

const SolveLazyImport = createFileRoute('/solve')()
const CreateLazyImport = createFileRoute('/create')()

// Create/Update Routes

const SolveLazyRoute = SolveLazyImport.update({
  path: '/solve',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./../../routes/solve.lazy').then((d) => d.Route))

const CreateLazyRoute = CreateLazyImport.update({
  path: '/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./../../routes/create.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      preLoaderRoute: typeof CreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/solve': {
      preLoaderRoute: typeof SolveLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CreateLazyRoute,
  SolveLazyRoute,
])

/* prettier-ignore-end */
